api_platform:
    title: "MTG Edition Game API"
    description: "The interal API of MTG Edition Game webapp"
    version: '0.1.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

